name: Proton nopackage Arch Linux CI

on:
  schedule:
    - cron: '25 9,21 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu --noconfirm base-devel sudo lib32-jack2 git

      - name: Setup user and install paru
        run: |
          useradd -m -G wheel -s /bin/bash user
          echo "user ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers

          # Switch to user and install paru
          sudo -u user bash -c "
            cd ~
            git clone https://aur.archlinux.org/paru.git
            cd paru
            makepkg -si --noconfirm
          "

      - name: Install ntsync-header
        run: sudo -u user paru -S ntsync-header --noconfirm

      - name: Compile Proton-TKG
        run: |
          chown -R user:user $PWD
          export CARGO_HOME="$PWD"
          cd proton-tkg
          sed -i 's/uninstaller="false"/uninstaller="true"/' proton-tkg.cfg
          sed -i 's/autoinstall="false"/autoinstall="true"/' proton-tkg.cfg
          sed -i 's/LOCAL_PRESET=""/LOCAL_PRESET="none"/' proton-tkg.cfg
          sed -i 's/build_gstreamer="false"/build_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/lib32_gstreamer="false"/lib32_gstreamer="true"/' proton-tkg.cfg
          sed -i 's/wayland_driver="false"/wayland_driver="true"/' proton-tkg.cfg
          touch tarplz
          yes | sudo -u user ./proton-tkg.sh

      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proton-tkg-build
          path: proton-tkg/built/*.tar
